version: '3'
services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./services/api:/app
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - mynetwork

  web:
    build:
      context: ./services/web
      dockerfile: dockerFile
      args:
        - VITE_APP_URL=${VITE_APP_URL}
        - VITE_API_URL=${VITE_API_URL}
    working_dir: /app
    volumes:
      - ./services/web:/app
    env_file:
      - .env
    ports:
      - '5173:5173'
    command: npm run dev
    networks:
      - mynetwork

  db:
    image: postgres:15
    volumes:
      - ./storage/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - mynetwork

networks:
  mynetwork:
