version: '3'
services:
  db:
    image: postgres:15
    volumes:
      - ./storage/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - mynetwork

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile.production
      args:
        - DATABASE_URL=${DATABASE_URL}
    working_dir: /app
    volumes:
      - ./services/api:/app
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - mynetwork

  nginx:
    build:
      context: ./services/web
      dockerfile: dockerFile.production
      args:
        - VITE_APP_URL=${VITE_APP_URL}
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - mynetwork

networks:
  mynetwork:
