services:
  db:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  api:
    build:
      context: ./services/api
      dockerfile: dockerFile.Production
    working_dir: /app
    volumes:
      - ./data/api/logs:/app/logs
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test:
        ['CMD-SHELL', 'curl -f http://localhost:3000/api/v1/health || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  nginx:
    build:
      context: ./services/web
      dockerfile: dockerFile.Production
    container_name: nginx
    volumes:
      - ./data/nginx/logs:/var/log/nginx
      - ./services/nginx/production/conf.d:/etc/nginx/conf.d
      - ./services/nginx/certs:/etc/nginx/certs
    depends_on:
      - api
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
