FROM node:20-bullseye AS build

WORKDIR /app

COPY ./web/package*.json ./

RUN npm install

COPY ./web .

RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/../nginx/production/conf.d/default.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
