FROM node:18-alpine as builder

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production
RUN npm i typescript

COPY . .

ARG VITE_APP_URL
ARG VITE_API_URL

ENV VITE_APP_URL=${VITE_APP_URL}
ENV VITE_API_URL=${VITE_API_URL}

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist/ /usr/share/nginx/html