FROM node:20-bullseye AS dev

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:20-bullseye AS prod

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production

COPY --from=dev /app/dist ./dist

CMD ["npm", "run", "start"]
