FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install --only=production
RUN npm i typescript

COPY . .

RUN npm run prisma:generate

RUN npm run build

FROM node:18

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/. ./.

CMD ["npm", "run", "docker:start:prod"]